# Generated by Django 5.1.1 on 2026-08-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_activitylog_taskattachment_taskcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total authorized budget in INR (₹)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Realized cost in INR (₹)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_hours',
            field=models.PositiveIntegerField(default=0, help_text='Realized effort in man-hours'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated cost in INR (₹)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=0, help_text='Estimated effort in man-hours'),
        ),
    ]
