# Generated by Django 5.1.1 on 2026-08-29 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_owner'),
        ('teams', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='teams.team'),
        ),
    ]
